services:
  - type: web
    name: hospital-management-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hospital_management_system.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString

databases:
  - name: hospital-db
    plan: free
